name: accouchement
up:
  - homebrew:
    - openssl
  - go: 1.7.5
  - railgun
commands:
  build: make build
  test: make test
  server: bin/accouchement serve --redis=redis://@192.168.64.42:6379 --port=4242
  grok: ngrok http 4242
  notify: bin/accouchement notify --redis=redis://@192.168.64.42:6379 --port=4242
railgun:
  image: dev:railgun-common-services-0.2.x
  services:
    nginx: 80
    redis: 6379
  ip_address: 192.168.64.42
  memory: 2G
  cores: 2
  disk: 2G

packages:
  - git@github.com:Shopify/dev-shopify.git
